studentsdb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from .settings import MEDIA_ROOT, DEBUG
# from students.views.students import StudentList
from students.views.contact_admin import ContactView
from students.views.groups import GroupDeleteView, GroupUpdateView, GroupAddView
from students.views.students import StudentUpdateView, StudentDeleteView, StudentAddView
from students.views.exam import ExamsUpdateView, ExamAddView, ExamsDeleteView
from students.views.journal import JournalView
from contact_form.views import ContactFormView
from contact_form import urls


urlpatterns = patterns('',
	# Students urls
	url(r'^$', 'students.views.students.students_list', name='home'),
#	url(r'^students/add/$', 'students.views.students.students_add',
#		name='students_add'),
	url(r'^students/add/$', StudentAddView.as_view(), name='students_add'),
	url(r'^students/(?P<pk>\d+)/edit/$', StudentUpdateView.as_view(),
		name='students_edit'),
#	url(r'^students/(?P<pk>\d+)/edit/$', 'students.views.students.students_edit',
#		name='students_edit'),
	url(r'^studetns/(?P<pk>\d+)/delete/$', StudentDeleteView.as_view(),
		name='students_delete'),
		
	# Group urls
	url(r'^groups/$', 'students.views.groups.groups_list', name='groups'),
	url(r'^groups/add/$', GroupAddView.as_view(), name='groups_add'),
#	url(r'^groups/add/$', 'students.views.groups.groups_add',
#		name='groups_add'),
	url(r'^groups/(?P<pk>\d+)/edit/$', GroupUpdateView.as_view(), name='groups_edit'),

#	url(r'^groups/(?P<pk>\d+)/edit/$', 'students.views.groups.groups_edit',
#		name='groups_edit'),
	url(r'^groups/(?P<pk>\d+)/delete/$', GroupDeleteView.as_view(), name='groups_delete'),
		
	# Journal
#	url(r'^journal/$', 'students.views.journal.journal_list', name='journal'),
	url(r'^journal/(?P<pk>\d+)?/?$', JournalView.as_view(), name='journal'),
		
	# Exams
    url(r'^exams/$', 'students.views.exam.exams_list', name='exams'),
    url(r'^exams/add/$', ExamAddView.as_view(), name='exams_add'),
	url(r'^exams/(?P<pk>\d+)/edit/$', ExamsUpdateView.as_view(), name='exams_edit'),
   
#    url(r'^exams/(?P<pk>\d+)/edit/$', 'students.views.exam.exams_edit', 
#		name='exams_edit'),
    url(r'^exams/(?P<pk>\d+)/delete/$', ExamsDeleteView.as_view(), name='exams_delete'),
	
	# Admin	
    url(r'^admin/', include(admin.site.urls), name='admin'),

	# Contact Admin Form
	url(r'^contact-admin/$', ContactView.as_view(), name='contact_admin'),

#	url(r'^contact-admin/$', 'students.views.contact_admin.contact_admin', 
#		name='contact_admin')

	# Contact Admin Form django-contact-form 1.1
#	url(r'^contact-admin/$', include(urls), name='contact_admin')

)
	

	

if DEBUG:
	urlpatterns += patterns('',
		url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
			'document_root': MEDIA_ROOT}))

students/models.py
# -*- coding: utf-8 -*-

from django.db import models

# Create your models here.
class Student(models.Model):
	"""Student Model"""
	
	class Meta(object):
		verbose_name = u"Студент"
		verbose_name_plural = u"Студенти"
	
	first_name = models.CharField(
		max_length=256,
		blank=False,
		verbose_name=u"Прізвище")
	
	last_name = models.CharField(
		max_length=256,
		blank=False,
		verbose_name=u"Ім’я")
		
	middle_name = models.CharField(
		max_length=256,
		blank=True,
		verbose_name=u"По-батькові",
		default='')
		
	birthday = models.DateField(
		blank=False,
		verbose_name=u"Дата народження",
		null=True)
		
	photo = models.ImageField(
		blank=True,
		verbose_name=u'Фото',
		null=True)
		
	ticket = models.IntegerField(
		blank=False,
		verbose_name=u"Білет")
		
	student_group = models.ForeignKey('Group',
		verbose_name=u'Група',
		blank=False,
		null=True,
		on_delete=models.PROTECT)
		
	notes = models.TextField(
		blank=True,
		verbose_name=u"Додаткові нотатки")
	
	def __unicode__(self):
		return u"%s %s" % (self.first_name, self.last_name)

class Group(models.Model):
	"""Group Model"""
	
	class Meta(object):
		verbose_name = u"Група"
		verbose_name_plural = u"Групи"
	
	title = models.CharField(
		max_length=256,
		blank=False,
		verbose_name=u"Назва")
	
	leader = models.OneToOneField('Student',
		verbose_name=u"Староста",
		blank=True,
		null=True,
		on_delete=models.SET_NULL)
		
	notes = models.TextField(
		blank=True,
		verbose_name=u"Додаткові нотатки")
	
	def __unicode__(self):
		if self.leader:
			return u"%s (%s %s)" % (self.title, self.leader.first_name, self.leader.last_name)
		else:
			return u"%s" % (self.title,)

students/models/exams.py
# -*- coding: utf-8 -*-

from django.db import models

# Create your models here.
class Exam(models.Model):
	class Meta(object):
		verbose_name = u"Екзамен"
		verbose_name_plural = u"Екзамени"
		
	matter = models.CharField(
		verbose_name = u"Предмет",
		max_length = 256,
		blank = False,
		null = False)
		
	time = models.DateTimeField(
		verbose_name = u"Час проведення",
		blank = False,
		null = False)
		
	teacher = models.CharField(
		verbose_name = u"Викладач",
		max_length = 256,
		blank = False,
		null = False)
		
	group_exam = models.ForeignKey('Group',
		verbose_name = u"Група",
		blank = False,
		null = False)
		
	def __unicode__(self):
		return u"%s (%s)" % (self.matter, self.group_exam.title)

students/models/groups.py
# -*- coding: utf-8 -*-

from django.db import models

class Group(models.Model):
	"""Group Model"""
	
	class Meta(object):
		verbose_name = u"Група"
		verbose_name_plural = u"Групи"
	
	title = models.CharField(
		max_length=250,
		blank=False,
		unique=True,
		error_messages={'unique': 'Група з такою назвою вже існує'},
		verbose_name=u"Назва")
	
	leader = models.OneToOneField('Student',
		verbose_name=u"Староста",
		blank=True,
		null=True,
		error_messages={'unique': 'Група з таким старостою вже існує'},
		on_delete=models.SET_NULL)
		
	notes = models.TextField(
		blank=True,
		verbose_name=u"Додаткові нотатки")
	
	def __unicode__(self):
		if self.leader:
			return u"%s (%s %s)" % (self.title, self.leader.first_name, self.leader.last_name)
		else:
			return u"%s" % (self.title,)
			

students/models/journal.py
# -*- coding: utf-8 -*-

from django.db import models

# Create your models here.
class Student_visiting(models.Model):
	
	class Meta(object):
		verbose_name = u"Відвідування"
		verbose_name_plural = u"Відвідування"
		
	student_name = models.OneToOneField('Student',
		verbose_name = u"Студент",
		blank = False,
		null = True)
		
	visiting = models.IntegerField(
		max_length = 5,
		blank = True,
		null = True)

	def __unicode__(self):
		return "%s %s" % (self.student_name.first_name, self.student_name.last_name)
		

students/models/students.py
# -*- coding: utf-8 -*-

from django.db import models

# Create your models here.
class Student(models.Model):
	"""Student Model"""
	
	class Meta(object):
		verbose_name = u"Студент"
		verbose_name_plural = u"Студенти"
	
	first_name = models.CharField(
		max_length=256,
		blank=False,
		verbose_name=u"Прізвище")
	
	last_name = models.CharField(
		max_length=256,
		blank=False,
		verbose_name=u"Ім’я")
		
	middle_name = models.CharField(
		max_length=256,
		blank=True,
		verbose_name=u"По-батькові",
		default='')
		
	birthday = models.DateField(
		blank=False,
		verbose_name=u"Дата народження",
		null=True)
		
	photo = models.ImageField(
		blank=True,
		verbose_name=u'Фото',
		null=True)
		
	ticket = models.IntegerField(
		blank=False,
		verbose_name=u"Білет")
		
	student_group = models.ForeignKey('Group',
		verbose_name=u'Група',
		blank=False,
		null=True,
		on_delete=models.PROTECT)
		
	notes = models.TextField(
		blank=True,
		verbose_name=u"Додаткові нотатки")
	
	def __unicode__(self):
		return u"%s %s" % (self.first_name, self.last_name)

students/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse

# Views for Students

def students_list(request):
	students = (
		{'id': 1,
		 'first_name': u'Вейдер',
		 'last_name': u'Дарт',
		 'ticket': 27,
		 'image': 'img/SOS.JPG'},
		 {'id': 2,
		 'first_name': u'Мелфой',
		 'last_name': u'Люціус',
		 'ticket': 618,
		 'image': 'img/Mich.JPG'},
		 {'id': 3,
		 'first_name': u'Бендер',
		 'last_name': u'Остап',
		 'ticket': 411,
		 'image': 'img/Kir.JPG'},
	)
	groups = (
		{'id': 1,
		 'name': u'1Б-04',
		 'leader': {'id': 4, 'name': u'Бацура Олександр'}},
		{'id': 2,
		 'name': u'2Б-04',
		 'leader': {'id': 5, 'name': u'Козаченко Богдан'}},
		{'id': 3,
		 'name': u'БМ-04',
		 'leader': {'id': 2, 'name': u'Люціус Мелфой'}},
		 )
	return render(request, 'students/students_list.html', 
		{'students': students, 'groups': groups})

def students_add(request):
	return HttpResponse('<h1>Student Add Form</h1>')
	
def students_edit(request, sid):
	return HttpResponse('<h1>Edit Student %s</h1>' % sid)
	
def students_delete(request, sid):
	return HttpResponse('<h1>Delete Student %s</h1>' % sid)
	
# Views for Groups

def groups_list(request):
	groups = (
		{'id': 1,
		 'name': u'1Б-04',
		 'leader': {'id': 4, 'name': u'Бацура Олександр'}},
		{'id': 2,
		 'name': u'2Б-04',
		 'leader': {'id': 5, 'name': u'Козаченко Богдан'}},
		{'id': 3,
		 'name': u'БМ-04',
		 'leader': {'id': 2, 'name': u'Люціус Мелфой'}},
		 )
	return render(request, 'students/groups_list.html', {'groups': groups})

def groups_add(request):
	return HttpResponse('<h1>Group Add Form</h1>')
	
def groups_edit(request, gid):
	return HttpResponse('<h1>Edit Group %s</h1>' % gid)
	
def groups_delete(request, gid):
	return HttpResponse('<h1>Delete Group %s</h1>' % gid)
	
# Views for Journal

def journal_list(request):
	return HttpResponse('<h1>Journal</h1>')

students/views/contact_admin.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django import forms
from django.contrib import messages
from django.core.mail import send_mail, mail_admins
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.bootstrap import FormActions, PrependedText
from crispy_forms.layout import Submit,  Div, Layout

from studentsdb.settings import ADMIN_EMAIL

from django.views.generic.edit import FormView

class ContactForm(forms.Form):
	def __init__(self, *args, **kwargs):
		# call original initializator
		super(ContactForm,self).__init__(*args,**kwargs)
		
		# this helper object allows us to customize form
		self.helper = FormHelper()
		
		# form tag attributes
		self.helper.form_class = 'form-horizontal'
		self.helper.form_method = 'post'
		self.helper.form_action = reverse('contact_admin')
		
		# twitter bootstrap styles
		self.helper.help_text_inline = True
		self.helper.html5_required = True
		self.helper.label_class = 'col-sm-2 control-label'
		self.helper.field_class = 'col-sm-10'
		
		# form buttons
		self.helper.layout = Layout(
			'from_email',
			'subject',
			'message',
			FormActions(
				Div('', css_class='col-sm-2'),
				Submit('send_button', u'Надіслати', css_class="btn btn-primary"),
				)
			)
	
	from_email = forms.EmailField(
		label=u"Ваша Email адреса")
		
	subject = forms.CharField(
		label=u"Заголовок листа",
		max_length=128)
		
	message = forms.CharField(
		label=u"Текст повідомлення",
		max_length=2560,
		widget=forms.Textarea)

class ContactView(FormView):
	template_name = 'contact_admin/contact_form.html'
	form_class = ContactForm
	success_url = '/contact-admin/'
	
	def form_valid(self, form):
		subject = form.cleaned_data['subject'] + '(' + form.cleaned_data['from_email'] + ')'
		message = form.cleaned_data['message']
		
		try: mail_admins(subject, message, 'trivvet@yahoo.com.ua')
		except Exception:
			messages.warning(self.request, u"Під час відправки листа виникла непередбачувана помилка. " \
				u"Спробуйте скористатися даною формою пізніше")
		else:
			messages.success(self.request, u'Повідомлення успішно надіслане')
		
		return super(ContactView, self).form_valid(form)


def contact_admin(request):
	# check if form was posted
	if request.method == "POST":
		# create a form instance
		form = ContactForm(request.POST)
		if form.is_valid():
			subject = form.cleaned_data['subject']
			message = form.cleaned_data['message']
			from_email = form.cleaned_data['from_email']
			
			try: send_mail(subject, message, from_email, [ADMIN_EMAIL])
			except Exception:
				messages.warning(request, u"Під час відправки листа виникла непередбачувана помилка. " \
					u"Спробуйте скористатися даною формою пізніше")
			else:
				messages.success(request, u'Повідомлення успішно надіслане')
				
			return HttpResponseRedirect(reverse('contact_admin'))
	else:
		form = ContactForm()
	
	return render(request, 'contact_admin/form.html', {'form': form})

students/views/journal.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponse, JsonResponse
from ..models.journal import Student_visiting
from ..models.monthjournal import MonthJournal
from ..models.students import Student
from ..models.groups import Group
from django.views.generic.base import TemplateView
from datetime import datetime, date
from dateutil.relativedelta import relativedelta
from calendar import monthrange, weekday, day_abbr
from ..views.paginator import page_scroll
import pdb
from ..util import get_current_group

class JournalView(TemplateView):
	template_name = 'students/journal.html'
	
	def get_context_data(self, **kwargs):
		context = super(JournalView, self).get_context_data(**kwargs)
		
		if self.request.GET.get('month'):
			month = datetime.strptime(self.request.GET['month'], '%Y-%m-%d').date()
		else:
			today = datetime.today()
			month = date(today.year, today.month, 1)
		
		next_month = month + relativedelta(months=1)
		prev_month = month - relativedelta(months=1)
		context['prev_month'] = prev_month.strftime('%Y-%m-%d')
		context['next_month'] = next_month.strftime('%Y-%m-%d')
		context['year'] = month.year
		context['cur_month'] = month.strftime('%Y-%m-%d')
		context['month_verbose'] = month.strftime('%B')
		
		myear, mmonth = month.year, month.month
		number_of_days = monthrange(myear,mmonth)[1]
		context['month_header'] = [
			{'day': d, 'verbose': day_abbr[weekday(myear,mmonth,d)][:2]}
				for d in range(1, number_of_days+1)]
			
		if kwargs.get('pk'):
			queryset = [Student.objects.get(pk=kwargs['pk'])]
		else:
			current_group = get_current_group(self.request)
			if current_group:
				queryset = Student.objects.filter(student_group=current_group)
			else:
				queryset = Student.objects.all()
		
		order_by = self.request.GET.get('order_by', '')
		if order_by:
			queryset = queryset.order_by(order_by)
			if self.request.GET.get('reverse', '') == '1':
				queryset = queryset.reverse()
			
		update_url = reverse('journal') 
		
		students = []
		
		for student in queryset:
			try:
				journal = MonthJournal.objects.get(student=student, date=month)
			except:
				journal = None
			days = []
			for day in range(1,number_of_days+1):
				days.append({
					'day': day,
					'present': journal and getattr(journal, 'present_day%d' 
						% day, False) or False,
					'date': date(myear, mmonth, day).strftime('%Y-%m-%d'),
					'verbose_date': date(myear, mmonth, day).strftime('%w'),
					})
			students.append({
				'full_name': u'%s %s' % (student.first_name, student.last_name),
				'days': days,
				'id': student.id,
				'update_url': update_url,
				})
		
		context['pages'] = page_scroll(students, 10)
			
		page = int(self.request.GET.get('page', '1'))
		context['page'] = (page - 1) * 10
		if len(context['pages']) <= 1:
			context['students'] = students
		else:
			context['students'] = students[(page - 1)*10:page*10]
			
		return context
		
	def post(self, request, *args, **kwargs):
		data = request.POST
		current_date = datetime.strptime(data['date'], '%Y-%m-%d').date()
		month = date(current_date.year, current_date.month, 1)
		present = data['present'] and True or False
		student = Student.objects.get(pk=data['pk'])
		journal = MonthJournal.objects.get_or_create(student=student, date=month)[0]
		
		setattr(journal, 'present_day%d' % current_date.day, present)
		journal.save()
		
		return JsonResponse({'status': 'success'})

def journal_list(request):
	students = Student_visiting.objects.all()
	
	order_by = request.GET.get('order_by', '')
	if order_by in ('id', 'student_name__first_name'):
		students = students.order_by(order_by)
		if request.GET.get('reverse', '') == '1':
			students = students.reverse()
	else:
		students = students.order_by('id')
		
	pages = []
	k = 0
	if not students.count() % 3 == 0:
		k = 1
	for i in range(students.count() / 5 + k):
		pages.append(str(i+1))
		
	number_page = int(request.GET.get('page', '1'))
	if number_page > len(pages):
		number_page = len(pages) - 3
		number_page = len(pages)
	students = students[number_page * 3 - 3: number_page * 3]
		
	days = '111111111111111111111111111111'	
	
	groups = Group.objects.all()
	return render(request, 'students/journal_list.html', {'students': students, 'groups': groups, 'pages': pages, 'days': days})

students/views/paginator.py
def page_scroll(list_smt, n):
	pages = []
	k = 0
	if len(list_smt) % n == 0:
		k = len(list_smt) / n
	else:
		k = len(list_smt) / n + 1
	for page in range(k):
		pages.append(str(page+1))
	return pages

students/templates/students/exams_add.html
{% extends "students/base.html" %}

{% load static from staticfiles %}

{% load crispy_forms_tags %}

{% block meta_title %}Додати екзамен{% endblock meta_title %}

{% block title %}Додати екзамен{% endblock title %}

{% block content %}

{% crispy form %}

<!--
<form action="." method="post" class="form-horizontal">
{% csrf_token %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span {% if errors %}style="color:red; font-size=0.8em>"{% endif %}>
				* Обов’язкові поля</span>
		</div>
	</div>
	<div class="form-group {% if errors.matter %}has-error{% endif %}">
		<label for="matter" class="col-sm-2 control-label">
			Предмет <span {% if errors.matter %}style="color:red"{% endif %}
				>*</span></label>
		<div class="col-sm-10">
			<input id="matter" name="matter" type="text" class="form-control"
				value="{{ request.POST.matter }}"
				placeholder="Введіть назву предмету">
			<span class="help-block">{{ errors.matter }}</span>
		</div>
	</div>
	<div class="form-group {% if errors.time %}has-error{% endif %}">
		<label for="time" class="col-sm-2 control-label">Дата проведення 
			<span {% if errors.matter %}style="color:red"{% endif %}
				>*</span></label>
		<div class="col-sm-10">
			<div class='input-group date' id='datetimeinput'>
				<input id="time" name="time" type="text" class="form-control"
					value="{{ request.POST.time }}"
					placeholder="YYYY-MM-DD HH-MM">
				<span class='input-group-addon'>
					<span class="glyphicon glyphicon-calendar"></span>
				</span>
			</div>
			<span class="help-block">{{ errors.time }}</span>
		</div>
	</div>
	<div class="form-group {% if errors.teacher %}has-error{% endif %}">
		<label for="teacher" class="col-sm-2 control-label">Викладач 
			<span {% if errors.teacher %}style="color:red"{% endif %}
				>*</span></label>
		<div class="col-sm-10">
			<input id="teacher" name="teacher" type="text" class="form-control"
				value="{{ request.POST.teacher }}"
				placeholder="Введіть прізвище та ініціали викладача">
			<span class="help-block">{{ errors.teacher }}</span>
		</div>
	</div>
	<div class="form-group {% if errors.group_exam %}has-error{% endif %}">
		<label for="group_exam" class="col-sm-2 control-label">Група 
			<span {% if errors.group_exam %}style="color:red"{% endif %}
				>*</span></label>
		<div class="col-sm-10">
			<select id='group_exam' name='group_exam' class="form-control">
				<option value=''>Виберіть групу</option>
				{% for group in groups %}
				<option value='{{ group.id }}'>
					{{ group.title }}
				</option>
				{% endfor %}
			</select>
			<span class="help-block">{{ errors.group_exam }}</span>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-primary" name="add_button">Додати</button>
			<input type="submit" class="btn btn-link" name="cancel_button" value='Скасувати' />
		</div>
	</div>
</form>
-->
{% endblock content %}

students/templates/students/exams_edit_class.html
{% extends "students/base.html" %}

{% load static from staticfiles %}

{% load crispy_forms_tags %}

{% block meta_title %}Редагувати екзамен{% endblock meta_title %}

{% block title %}Редагувати екзамен{% endblock title %}

{% block messages %}
{% if form.errors %}
	<div class='alert alert-danger'>
		Будь-ласка виправте наступні помилки
	</div>
{% endif %}
{% endblock messages %}

{% block content %}

{% crispy form %}

{% endblock content %}

students/templates/students/groups_edit_class.html
{% extends "students/base.html" %}

{% load crispy_forms_tags %}

{% block meta_title %}Форма додавання групи{% endblock meta_title %}

{% block title %}Форма додавання групи{% endblock title %}

{% block content %}

{% crispy form %}

{% endblock content %}

students/templates/students/students_add.html
{% extends "students/base.html" %}

{% load static from staticfiles %}

{% load crispy_forms_tags %}

{% block meta_title %}Додати студента{% endblock meta_title %}

{% block title %}Додати студента{% endblock title %}

{% block content %}



<!--
<form class="form-horizontal" action="{% url "students_add" %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="form-group">
		<div class="col-sm-2"></div>
		<div class="col-sm-10">
			<span {% if errors %}style="color:red; font-size:0.8em"{% endif %}>
				* Обов’язкове поле
			</span></div>
	</div>
	<div class="form-group {% if errors.first_name %}has-error{% endif %}">
		<label class="col-sm-2 control-label" for="first_name">
			Прізвище 
			<span {% if errors.first_name %}style="color:red"{% endif %}>
				*
			</span>
		</label>
		<div class="col-sm-10">
			<input type="text" value="{{ request.POST.first_name }}" 
				class="form-control" name="first_name"
				id="first_name" placeholder="Введіть прізвище" />
			<span class="help-block	">{{ errors.first_name }}</span>
		</div>
	</div>
	<div class="form-group {% if errors.last_name %}has-error{% endif %}">
		<label class="col-sm-2 control-label" for="last_name">
			Ім’я 
			<span {% if errors.first_name %}style="color:red"{% endif %}>
				*
			</span>
		</label>
		<div class="col-sm-10">
			<input type="text" value="{{ request.POST.last_name }}" 
				class="form-control" name="last_name"
				id="last_name" placeholder="Введіть ім’я" />
			<span class="help-block	">{{ errors.last_name }}</span>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-2 control-label" for="middle_name">
			По-батькові
		</label>
		<div class="col-sm-10">
			<input type="text" value="{{ request.POST.middle_name }}" 
				class="form-control" name="middle_name"
				id="middle_name" placeholder="Введіть ім’я по-батькові" />
		</div>
	</div>
	<div class="form-group {% if errors.birthday %}has-error{% endif %}">
		<label class="col-sm-2 control-label" for="birthday">
			Дата народження 
			<span {% if errors.first_name %}style="color:red"{% endif %}>
				*
			</span>
		</label>
		<div class="col-sm-10">
			<div id="id_birthday" class="input-group date">
				<input type="text" value="{{ request.POST.birthday }}" 
					class="form-control dateinput" name="birthday" 
					id="birthday" placeholder="YYYY-MM-DD" />
				<span class='input-group-addon'>
					<span class="glyphicon glyphicon-calendar"></span>
				</span>
				<span class="help-block	">{{ errors.birthday }}</span>
			</div>
		</div>
	</div>
	<div class="form-group {% if errors.photo %}has-error{% endif %}">
		<label class="col-sm-2 control-label" for="photo">
			Фото
		</label>
		<div class="col-sm-10">
			<input type="file" value=""
				name="photo" id="photo" placeholder="1986-12-12" />
			<span class="help-block">{{ errors.photo }}</span>
		</div>
	</div>
	<div class="form-group {% if errors.ticket %}has-error{% endif %}">
		<label class="col-sm-2 control-label" for="ticket">
			№ білету 
			<span {% if errors.first_name %}style="color:red"{% endif %}>
				*
			</span>
		</label>
		<div class="col-sm-10">
			<input type="text" value="{{ request.POST.ticket }}" 
				class="form-control" name="ticket" id="ticket" 
				placeholder="Введіть номер білету" />
			<span class="help-block">{{ errors.ticket }}</span>
		</div>
	</div>
	<div class="form-group {% if errors.student_group %}has-error{% endif %}">
		<label class="col-sm-2 control-label" for="student_group">
			Група 
			<span {% if errors.first_name %}style="color:red"{% endif %}>
				*
			</span>
		</label>
		<div class="col-sm-10">
			<select name="student_group" id="student_group" class="form-control" />
				<option value="">Виберіть групу</option>
				{% for group in groups %}
				<option value="{{ group.id }}" 
					{% if group.id == request.POST.student_group|add:0 %}
					selected="1" {% endif %}>
					{{ group.title }}
				</option>
				{% endfor %}
			</select>
			<span class="help-block">{{ errors.student_group }}</span>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-2 control-label" for="notes">
			Додаткові нотатки
		</label>
		<div class="col-sm-10">
			<textarea class="form-control" rows="3" 
				name="notes" id="notes">{{ request.POST.notes }}</textarea>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-2 control-label"></label>
		<div class="col-sm-10">
			<button type="submit" class="btn btn-primary" name="add_button">Зберегти</button>
			<button type="submit" class="btn btn-close" style="margin-left:10px"
				name="cancel_button">Скасувати</button>
		</div>
	</div>
</form>
-->

{% crispy form %}

{% endblock content %}